### PR TITLE
Fixes LCLabel not being able to behave properly when `.bottomAnchor` 

### LINKED ISSUE #34: Issues with NSConstraintLayout
Issues with NSConstraintLayout especially when using it with`greaterToOrEqual`.

@joeboyscout04 if possible let's update the ticket here.

### PR DESCRIPTION
**Pull request by mustiikhalil**
Fixes LCLabel not being able to behave properly when `.bottomAnchor`  constraint is used with `lessThanOrEqualTo`

closes #34

### CODE REVIEW

**Comment by mustiikhalil** [comment]
Got the chance to look into this, and the issue is somewhere in the intrinsicContentSize, where apple does some type of magic to create the perfect fit.

In the example below, this was a subclass of UILabel without any modifications. Just a couple of print statements.
```
### intrinsicContentSize:  (65536.0, 19.333333333333332)
### intrinsicContentSize:  (65536.0, 19.333333333333332)
### textRect bounds: (0.0, 0.0, 390.0, 3.4028234663852886e+38)
### return value: (2.0, 0.0, 385.6666666666667, 57.333333333333336)
### intrinsicContentSize:  (385.6666666666667, 57.333333333333336)
### intrinsicContentSize:  (65536.0, 19.333333333333332)
### intrinsicContentSize:  (385.6666666666667, 57.333333333333336)
## layoutSubviews bounds: (0.0, 0.0, 390.0, 57.333333333333336) frame: (0.0, 0.0, 390.0, 57.333333333333336)
## layoutSubviews bounds: (0.0, 0.0, 390.0, 57.333333333333336) frame: (0.0, 0.0, 390.0, 57.333333333333336)
### draw: (0.0, 0.0, 390.0, 57.33333333333333)
drawText:  (0.0, 0.0, 390.0, 57.333333333333336)
```

It's clear that apple is setting the width of the bounds as the width of the screen (Even if the super view isn't set just yet.)
Which will return the following bounds `(0.0, 0.0, 390.0, 3.4028234663852886e+38)` as the intrinsicContentSize

Mimicking that behavior:
```
### bounds:  (0.0, 0.0)
### windowSize:  (390.0, 0.0)
### bounds:  (390.0, 57.333333333333336)
### windowSize:  (390.0, 57.333333333333336)
```

**Comment by joeboyscout04** [comment]
I tested a bit, but this change didn't solve my [test case](https://github.com/mustiikhalil/LCLabel/tree/autolayout-tests).  The stackView is probably a red herring - I think it has something to do with calculating the intrinsicContentSize still.

**Comment by joeboyscout04** [comment]
Using the test case I linked above, here's a comparison between LCLabel and UILabel.  The only thing I've done is swap the class name (and remove the line which sets the `centeringTextAlignment` property)

UILabel
UILabel

LCLabel
LCLabel

**Comment by joeboyscout04** [comment]
One other thing I noticed is that within this function

```
  public override func textRect(
    forBounds bounds: CGRect,
    limitedToNumberOfLines numberOfLines: Int)
    -> CGRect
  {
  ```
The `limitedToNumberOfLines` variable isn't used anywhere within the function body.  This seems suspicious to me.  The error only occurs with numberOfLines == 0.

**Review by joeboyscout04 — CHANGES_REQUESTED** [review]
See comments above.

**Comment by mustiikhalil** [comment]
Well, we are in the correct path, its just that apple like to do stuff in a weird way :D 

First:
`### textRect bounds: (0.0, 0.0, 390.0, 3.4028234663852886e+38)`first the height is infinity here. so that's fixed.

Second:
`window?.windowScene?.screen.bounds.width` is nil if we have a superview, which then requires us to us superView.bounds.width

**Comment by mustiikhalil** [comment]
@joeboyscout04 Fixed :D we were on the right path, just another test case we didn't account for

**Review by joeboyscout04 — APPROVED** [review]
Nice work! Tests look good.

**Pull request merged**
